version: "3"

networks:
  giteanet:
    name: giteanet
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 192.168.237.0/24

  backend:
    name: backend
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 192.168.239.0/24

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1001 # Enter the UID found from previous command output
      - USER_GID=100  # Enter the GID found from previous command output
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - giteanet
      - backend
    volumes:
      - ./data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - backend
    volumes:
      - ./data/mysql:/var/lib/mysql

  pma:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 3001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=gitea
      - PMA_PASSWORD=gitea
    networks:
      - giteanet
      - backend

# Using this docker-compose configuration we will be deploying two containers which are gitea and mysql
# In order to make the mysql container accessible from the gitea container we need to specify environment variables with the required details
# Notice the Host is specified as "GITEA__database__HOST=db:3306" where "db" is the name of the mysql container i.e, if the name of the container is changed the host environment variable must also be updated accordingly
# All other environment variables are self explanatory where the User name and password needs to be specified for the databse
# The environment variable "USER_UID=1000" and "USER_GID=100" will have the UID and GID of the current user which can be obtained as shown in the previous step
# The port parameter "3000:3000" and "222:22" specifies the port mapping where the left port denotes the host port and the right port denotes the container port
# For the Port 22 notice that the host port is not 22. This is because the SSH port of the host is also 22. To avoid the clash between the host ssh port and container ssh port we need to specify a different port for this
# The volume mounts will create two folders "gitea" and "mysql" inside the project folder created previously
# For these containers a new network called "gitea" will be created and both will be a part of this network
# Save the file
